/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Panels.Insertarvideo;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import recursograficoscom.Barras;
import recursograficoscom.Botones;
import recursograficoscom.Fondo;

/**
 *
 * @author Durfen
 */

//Clase que muestra video para posterior correción
public class CorrecionVideo extends javax.swing.JFrame {
    //elementos lógicos
    private int idusuario, idcorrecion;
    String url;
    //elementos gráficos
    private Fondo fondo = new Fondo();
    private Dimension dim = new Dimension();
    private Barras barrasupe = new Barras();
    private Botones botoncorregir1 = new Botones();
    
    //constructor
    public CorrecionVideo(int idusuario,int idcorrecion, String url) {
        
        this.idusuario = idusuario;
        this.idcorrecion = idcorrecion;
        this.url = url;
        initComponents();
        iniciarcomponentes();
        setVisible(true);
        
    }
    //Se inicia de manera manual
    private void iniciarcomponentes(){
        setIconImage (new ImageIcon(getClass().getResource("/Imagenescomun/Logo.png")).getImage());
        System.out.println(idcorrecion);
        setResizable(false); 
        setLocationRelativeTo(null);
        
        //Jpanel que contiene JavaFX
        Insertarvideo is = new Insertarvideo(url);
        add(barrasupe);
        add(fondo);
        barrasupe.setBounds(0, 0, 950, 20);
        fondo.setBounds(0, 0, 5888, 600);
        is.setVisible(true);
        is.setBounds(80, 30, 800, 630);
        this.getContentPane().add(is);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoncorregir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botoncorregir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/next.png"))); // NOI18N
        botoncorregir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncorregirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(886, Short.MAX_VALUE)
                .addComponent(botoncorregir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(botoncorregir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncorregirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncorregirMouseClicked
        // TODO add your handling code here:
        CorrecionPronunciacion correcion = new CorrecionPronunciacion(idusuario, idcorrecion);
        dispose();

    }//GEN-LAST:event_botoncorregirMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botoncorregir;
    // End of variables declaration//GEN-END:variables
}
