/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Funcionamiento.Leer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import recursograficoscom.Barras;
import recursograficoscom.Fondo;
import javax.swing.JOptionPane;

/**
 *
 * @author Durfen
 */
public class Inicio extends javax.swing.JFrame {

    //elementos gráficos
    private Barras barrasupe = new Barras();
    private Barras barrainfe = new Barras();
    private Fondo fondo = new Fondo();
    private ImageIcon imgintroducc = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/introduccionboton.png")).getImage());
    private ImageIcon imggramatica = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/gramaticaboton.png")).getImage());
    private ImageIcon imgpronunciacion = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/pronunciacionboton.png")).getImage());
    private ImageIcon imgcompresionlectora = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/compresionlectoraboton.png")).getImage());
    private ImageIcon imgcompresionoral = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/COMPRESIONORAL.png")).getImage());
    private ImageIcon imgexpresion = new ImageIcon(new ImageIcon(getClass().getResource("/Imageninicio/EXPRESIONESCRITA.png")).getImage());
    //id usuario
    private int id = -1;

    /**
     * Creates new form Inicio
     */
    //Constructor
    public Inicio() {
        initComponents();
        iniciarcomponentes();
        Leer leer = new Leer();
        leer.leer();
        setSize(800,600);

        setVisible(true);
    }

    //Constructor de vuelta con el id después de login
    public Inicio(int id) {
        initComponents();
        iniciarcomponentes();
        Leer leer = new Leer();
        leer.leer();
        setVisible(true);
        this.id = id;

    }

    //componentes iniciados de manera manual
    private void iniciarcomponentes() {
        setIconImage (new ImageIcon(getClass().getResource("/Imagenescomun/Logo.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        add(barrasupe);
        add(barrainfe);
        add(fondo);
        botonintro.setIcon(imgintroducc);
        botongramatica.setIcon(imggramatica);
        botonpronunciacion.setIcon(imgpronunciacion);
        botoncomprelec.setIcon(imgcompresionlectora);
        botoncompreoral.setIcon(imgcompresionoral);
        botonexpresion.setIcon(imgexpresion);
        barrasupe.setBounds(0, 0, 920, 20);
        
        fondo.setBounds(0, 0, 5888, 600);

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonintro = new javax.swing.JLabel();
        botongramatica = new javax.swing.JLabel();
        botonpronunciacion = new javax.swing.JLabel();
        botoncomprelec = new javax.swing.JLabel();
        botoncompreoral = new javax.swing.JLabel();
        botonexpresion = new javax.swing.JLabel();
        correcionpares = new javax.swing.JLabel();
        botonlogin = new javax.swing.JLabel();
        crearusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelresultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(825, 600));

        botonintro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonintroMouseClicked(evt);
            }
        });

        botongramatica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botongramaticaMouseClicked(evt);
            }
        });

        botonpronunciacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonpronunciacionMouseClicked(evt);
            }
        });

        botoncomprelec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncomprelecMouseClicked(evt);
            }
        });

        botoncompreoral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncompreoralMouseClicked(evt);
            }
        });

        botonexpresion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonexpresionMouseClicked(evt);
            }
        });

        correcionpares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/correcionpares.png"))); // NOI18N
        correcionpares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correcionparesMouseClicked(evt);
            }
        });

        botonlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imageninicio/LOG IN.png"))); // NOI18N
        botonlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonloginMouseClicked(evt);
            }
        });

        crearusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imageninicio/crear usuario.png"))); // NOI18N
        crearusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearusuarioMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imageninicio/menuprincipalimagen.png"))); // NOI18N

        labelresultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/resultados.png"))); // NOI18N
        labelresultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelresultadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonlogin)
                .addGap(276, 276, 276))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelresultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botongramatica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonintro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonpronunciacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonexpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoncomprelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoncompreoral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correcionpares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(crearusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonintro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botongramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonpronunciacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botoncomprelec, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botoncompreoral, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonexpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(correcionpares, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(labelresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //eventos se pasa el id por el constructor de cada uno, si id = -1 no se considera logueado
    private void botonintroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonintroMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            Introduccion intro = new Introduccion(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botonintroMouseClicked

    private void botongramaticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botongramaticaMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            Gramatica grama = new Gramatica(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botongramaticaMouseClicked

    private void botonpronunciacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonpronunciacionMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            Expresionoral oral = new Expresionoral(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botonpronunciacionMouseClicked

    private void botoncomprelecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncomprelecMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            CompresionLectora lectora = new CompresionLectora(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botoncomprelecMouseClicked

    private void botoncompreoralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncompreoralMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            Video video = new Video(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botoncompreoralMouseClicked
    //Eventos de usuario
    private void botonloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonloginMouseClicked
        // TODO add your handling code here:
        Login login = new Login(id);
        dispose();
    }//GEN-LAST:event_botonloginMouseClicked

    private void crearusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearusuarioMouseClicked
        // TODO add your handling code here:
        CrearUsuario crear = new CrearUsuario(id);
        dispose();
    }//GEN-LAST:event_crearusuarioMouseClicked

    private void correcionparesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correcionparesMouseClicked
        // TODO add your handling code here:
        SeleccionCorrecion seleccion = new SeleccionCorrecion(id);
        dispose();
    }//GEN-LAST:event_correcionparesMouseClicked

    private void botonexpresionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonexpresionMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            Expresionescrita expresion = new Expresionescrita(id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_botonexpresionMouseClicked

    private void labelresultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelresultadosMouseClicked
        // TODO add your handling code here:
        if (id != -1) {
            labelresultados.disable();
            ResultadosFinales resultados = new ResultadosFinales(id);
            resultados.setVisible(true);
            
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes entrar como usuario");
        }
    }//GEN-LAST:event_labelresultadosMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botoncomprelec;
    private javax.swing.JLabel botoncompreoral;
    private javax.swing.JLabel botonexpresion;
    private javax.swing.JLabel botongramatica;
    private javax.swing.JLabel botonintro;
    private javax.swing.JLabel botonlogin;
    private javax.swing.JLabel botonpronunciacion;
    private javax.swing.JLabel correcionpares;
    private javax.swing.JLabel crearusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelresultados;
    // End of variables declaration//GEN-END:variables
}
