package Frames;

import Funcionamiento.Cifrardes;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import recursograficoscom.Fondo;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Durfen
 */
public class Login extends javax.swing.JFrame {
    //elementos gráficos
    private Fondo fondo = new Fondo();
    //elementos lógicos
    private int id;
    private ResultSet rs;
    private Connection cn = null;
    private final String ruta = "jdbc:mysql://db4free.net:3306/proyectoelena?autoReconnect=true&useSSL=false";
    private final String usuario = "durfen";
    private final String contraseña = "Mariobrostomija1";
    private Statement statement;
    private PreparedStatement pstatement;
    //clase cifrado
    private Cifrardes cifrar = new Cifrardes();
  
    //Constructor
    public Login(int id) {
        initComponents();
        iniciarcomponentes();
        this.id = id;
    }

    private void iniciarcomponentes() {
        setIconImage (new ImageIcon(getClass().getResource("/Imagenescomun/Logo.png")).getImage());
        setLocationRelativeTo(null);
        add(fondo);
        fondo.setBounds(0, 0, 5888, 600);
        setVisible(true);
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usariolabel = new javax.swing.JLabel();
        contrasenalabel = new javax.swing.JLabel();
        textusuario = new javax.swing.JTextField();
        textcontrasena = new javax.swing.JTextField();
        botonext = new javax.swing.JLabel();
        botonback = new javax.swing.JLabel();
        enunciado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usariolabel.setText("Usuario");

        contrasenalabel.setText("Contraseña");

        botonext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/next.png"))); // NOI18N
        botonext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonextMouseClicked(evt);
            }
        });

        botonback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/botonback.png"))); // NOI18N
        botonback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonbackMouseClicked(evt);
            }
        });

        enunciado.setText("Introduzca usuario y contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonext, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(usariolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(textusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(contrasenalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(textcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(enunciado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usariolabel)
                    .addComponent(textusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasenalabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonextMouseClicked
        try {
           
            //se carga el driver y se prepara la conexión
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection(ruta, usuario, contraseña);
            statement = cn.createStatement();
            //se ejecuta el query obteniendo el id del último usuario
            String s= "SELECT id FROM usuarios WHERE user ='"+textusuario.getText()+"' AND password = '"+cifrar.cifrar(textcontrasena.getText())+"'";
            //Se ejecuta el query
            rs = statement.executeQuery(s);
            if(rs.next()){
                id=rs.getInt(1);
                JOptionPane.showMessageDialog(null, "Usuario confirmado, disfruta del MOOC");
                Inicio inicio = new Inicio(id);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña erróneos");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonextMouseClicked

    private void botonbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonbackMouseClicked
        Inicio inicio = new Inicio(id);
        dispose();
    }//GEN-LAST:event_botonbackMouseClicked
    //evento listener donde se implementan la limitación de caracteres de usuario y contraseña   
    private void listener() {
        //se limita la posibilidad de escribir a 200 caracteres0
        
        textusuario.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {

                // Verificar si la tecla pulsada no es un digito
                if (textusuario.getText().length() == 16) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
        textcontrasena.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {

                // Verificar si la tecla pulsada no es un digito
                if (textcontrasena.getText().length() == 16) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonback;
    private javax.swing.JLabel botonext;
    private javax.swing.JLabel contrasenalabel;
    private javax.swing.JLabel enunciado;
    private javax.swing.JTextField textcontrasena;
    private javax.swing.JTextField textusuario;
    private javax.swing.JLabel usariolabel;
    // End of variables declaration//GEN-END:variables
}
