/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Panels.Fondosplash;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Durfen
 */
public class Splash extends javax.swing.JFrame implements Runnable{

    
    public Splash() {
        initComponents();
        iniciarcomponentes();
        this.setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        cerrar();
        
    }
    //inicia de manera mnual
    private void iniciarcomponentes(){
        Fondosplash fondos = new Fondosplash();
        add(fondos);
        Dimension tam = getSize();
        fondos.setBounds(0, 0, (int)tam.getWidth(), (int)tam.getHeight());
    }
   
    

    @Override
    public void run() {
        try {
            //cierra el frame después de 4 segundos
            Thread.sleep(4000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void cerrar(){
        Runnable run = this;
        Thread h1 = new Thread(run);
        h1.start();
        try {
            h1.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
        }
        Inicio inicio = new Inicio();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
