/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import recursograficoscom.Barras;
import recursograficoscom.Botones;
import recursograficoscom.Fondo;

/**
 *
 * @author Durfen
 */
public class TestVideo extends javax.swing.JFrame {
    private Barras barrasupe = new Barras();
    private ButtonGroup opciones = new ButtonGroup();
    private boolean[] resultado = {false,false,false,false,false};
    private int contador;
    private Fondo fondo = new Fondo();
    private int id;
     //contador para switch e id usuario
     
    /**
     * Creates new form NewJFrame
     */
    public TestVideo(int id) {
        contador = 1;
        this.id = id;
        initComponents();
        iniciarcomponentes();
        setVisible(true);
    }
    private void iniciarcomponentes(){
        setIconImage (new ImageIcon(getClass().getResource("/Imagenescomun/Logo.png")).getImage());
        opcion1.setContentAreaFilled(false);
        opcion2.setContentAreaFilled(false);
        opciones.add(opcion1);
        opciones.add(opcion2);
        add(barrasupe);
        add(fondo);
        barrasupe.setBounds(0, 0, 820, 20);
        fondo.setBounds(0, 0, 5888, 600);
        setLocationRelativeTo(null);
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado = new javax.swing.JLabel();
        opcion1 = new javax.swing.JRadioButton();
        opcion2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enunciado.setText("1. Puedes solicitar la tarjeta sanitaria en cualquier centro de salud.");

        opcion1.setText("Verdadero");

        opcion2.setText("Falso");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenescomun/next.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enunciados/enunciadotestnormal.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion2)
                    .addComponent(opcion1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(opcion1)
                .addGap(18, 18, 18)
                .addComponent(opcion2)
                .addGap(73, 73, 73)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //switch que identifica el ejercicio
        switch (contador) {
            
            
            case 1:     
                //
                if (opciones.getSelection() == opcion1.getModel()) {
                    
                        resultado[0] = true;
                        enunciado.setText("2. Antes de solicitar la tarjeta sanitaria tienes que tener un piso o casa.");
                        contador++;
                    
                } else {
                    resultado[0] = false;
                    enunciado.setText("2. No es necesario añadir tu teléfono móvil o correo.");
                    contador++;   
                }
                break;
            case 2:
                if (opciones.getSelection() == opcion2.getModel()) {
                    resultado[1] = true;
                    
                    enunciado.setText("3. La tarjeta te la entregan enseguida en la oficina.");
                    contador++;
                } else{
                    resultado[1] = false;
                    enunciado.setText("3. La tarjeta te la entregan enseguida en la oficina.");
                    contador++;
                    
                }
                
                break;
            case 3:
                if (opciones.getSelection() == opcion2.getModel()) {
                    resultado[2] = true;
                    enunciado.setText("4. El médico es la persona que decide si tus documentos están bien y te da la tarjeta.");
                    contador++;
                } else {
                    resultado[2] = false;
                    enunciado.setText("4. El médico es la persona que decide si tus documentos están bien y te da la tarjeta.");
                    contador++;
                    
                }
                
                break;
            case 4:
                if (opciones.getSelection() == opcion1.getModel()) {
                    resultado[3] = true;
                    enunciado.setText("5. Antes de ir al Instituto Nacional de la Seguridad Social necesitas tener el NIE y estar empadronado.");
                    contador++;
                } else {
                    resultado[3] = false;
                    enunciado.setText("5. Antes de ir al Instituto Nacional de la Seguridad Social necesitas tener el NIE y estar empadronado.");
                    contador++;
                    
                }
                
                break;
            case 5:
                if (opciones.getSelection() == opcion1.getModel()) {
                        resultado[4] = true;
                        enunciado.setText("5. Es necesario especificar tu país de origen.");
                        contador++;
                } else {
                    resultado[4] = false;
                    enunciado.setText("5. Es necesario especificar tu país de origen.");
                    contador++;
                }
                
                Resultados resultados = new Resultados(resultado,id,1);
                dispose();
                break;
        }

    }//GEN-LAST:event_jLabel2MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enunciado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    // End of variables declaration//GEN-END:variables
}
