/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import recursograficoscom.Barras;
import recursograficoscom.Botones;
import recursograficoscom.Fondo;


/**
 *
 * @author Durfen
 */
public class TestCompresion extends javax.swing.JFrame {
    // se declaran
    private Botones imgbotonext = new Botones();
    private Barras barrasupe = new Barras();
    private ButtonGroup opciones = new ButtonGroup();
    private boolean[] resultado = {false,false,false,false,false};
    private int contador;
    private Fondo fondo = new Fondo();
    private int id;

   

    //constructor
    public TestCompresion(int id) {
        initComponents();
        cambiarcomponentes();
        this.id = id;
        
    }


    private void cambiarcomponentes() {
        setIconImage (new ImageIcon(getClass().getResource("/Imagenescomun/Logo.png")).getImage());
        opcion1.setContentAreaFilled(false);
        opcion2.setContentAreaFilled(false);
        contador = 1;
        this.getContentPane().setBackground(Color.white);
        opciones.add(opcion1);
        opciones.add(opcion2);
        add(barrasupe);
        add(fondo);
        barrasupe.setBounds(0, 0, 820, 20);
        fondo.setBounds(0, 0, 5888, 600);
        nextboton.setIcon(imgbotonext.Botonnext());
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion1 = new javax.swing.JRadioButton();
        opcion2 = new javax.swing.JRadioButton();
        enunciado = new javax.swing.JLabel();
        nextboton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcion1.setText("Verdarero");

        opcion2.setBackground(new java.awt.Color(255, 255, 255));
        opcion2.setText("Falso");

        enunciado.setText("1. Para rellenar la solicitud de la tarjeta sanitaria necesitas el NIE o el pasaporte.");

        nextboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextbotonMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enunciados/enunciadotestnormal.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextboton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(opcion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opcion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(opcion1)
                .addGap(37, 37, 37)
                .addComponent(opcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(nextboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextbotonMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:ç
        //switch que identifica el ejercicio
        switch (contador) {
            case 1:     
                if (opciones.getSelection() == opcion2.getModel()) {
                    
                        resultado[0] = true;
                        enunciado.setText("2. No es necesario añadir tu teléfono móvil o correo.");
                        contador++;
                    
                } else {
                    resultado[0] = false;
                    enunciado.setText("2. No es necesario añadir tu teléfono móvil o correo.");
                    contador++;   
                }
                break;
            case 2:
                if (opciones.getSelection() == opcion1.getModel()) {
                    resultado[1] = true;
                    enunciado.setText("3. La tarjeta de extranjero y el pasaporte son el mismo documento.");
                    contador++;
                } else{
                    resultado[1] = false;
                    enunciado.setText("3. La tarjeta de extranjero y el pasaporte son el mismo documento.");
                    contador++;
                    
                }
                
                break;
            case 3:
                if (opciones.getSelection() == opcion2.getModel()) {
                    resultado[2] = true;
                    enunciado.setText("4. El médico es la persona que decide si tus documentos están bien y te da la tarjeta.");
                    contador++;
                } else {
                    resultado[2] = false;
                    enunciado.setText("4. El médico es la persona que decide si tus documentos están bien y te da la tarjeta.");
                    contador++;
                    
                }
                
                break;
            case 4:
                if (opciones.getSelection() == opcion1.getModel()) {
                    resultado[3] = true;
                    enunciado.setText("5. Es necesario especificar tu país de origen.");
                    contador++;
                } else {
                    resultado[3] = false;
                    enunciado.setText("5. Es necesario especificar tu país de origen.");
                    contador++;
                    
                }
                
                break;
            case 5:
                if (opciones.getSelection() == opcion1.getModel()) {
                        resultado[4] = true;
                } else {
                    resultado[4] = false;
                }
                
                Resultados resultados = new Resultados(resultado,id,2);
                
                dispose();
                break;
        }

    }//GEN-LAST:event_nextbotonMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel enunciado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nextboton;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion2;
    // End of variables declaration//GEN-END:variables

}
