/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Durfen
 */
public class fotocompresion extends javax.swing.JPanel {
    private ImageIcon img;
    private String ruta;
    /**
     * Creates new form Jpanelcompresion
     */
    public fotocompresion(String ruta) {
        this.ruta=ruta;
        initComponents();
        
        setVisible(true);
        
        
    }
    //se sobrescribe paint para poner de fondo la imagen
    @Override
    public void paintComponent(Graphics g){
        Dimension tam =getSize();
        img = new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage());
        g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
        
        
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
